# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20180930_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='article_image',
            new_name='image',
        ),
    ]
